trigger:
  - master

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build and Push to ACR
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              containerRegistry: "$(dockerRegistryServiceConnection)"
              repository: "$(imageRepository)"
              command: "buildAndPush"
              Dockerfile: "$(dockerfilePath)"
              tags: |
                $(Build.BuildId)
                latest
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.SourcesDirectory)/manifests"
              ArtifactName: "manifests"

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    jobs:
      - deployment: Deploy
        displayName: Deploy to AKS
        pool:
          vmImage: ubuntu-latest
        environment: "PlannerApp.plannerapp"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: KubernetesManifest@0
                  inputs:
                    action: "deploy"
                    kubernetesServiceConnection: $(kubernetesServiceConnection)
                    namespace: $(namespace)
                    manifests: |
                      "$(Agent.BuildDirectory)/manifests/plannerapp.yaml"
                      "$(Agent.BuildDirectory)/manifests/ingresss.yaml"
